### PR TITLE
module to read TEfficiencies and make corrections

### PR DESCRIPTION
**Pull request by mroguljic**
Similar to HistLoader, but to work with TEfficiencies (trigger for example). Only 1D are supported now, I could add support for 2D later on.

### CODE REVIEW

**Comment by lcorcodilos** [comment]
I don't expect this to break any tests since they are all python but I got it to compile without errors in interactive ROOT. @mroguljic could you checkout this change and test that whatever script you were using this in still works? (or you can link it here and I can try)

**Comment by mroguljic** [comment]
I pulled the changes and they seem to work with a minor tweak. When providing evaluation arguments, all three needed to be specified even though the module provides default values for y and z.
The switch from `evalArgs={'xval':'mjjHY'}` to `evalArgs={'xval':'mjjHY','yval':0,'zval':0}` works.

The cause of this behavior is MakeCall https://github.com/lcorcodilos/TIMBER/blob/dev/TIMBER/Analyzer.py#L1665. It is calling `triggerCorrection.eval(mjjHY, yval, zval)`, so I guess the fix would be there.

In any case, the module seems to be working as intended.

**Comment by lcorcodilos** [comment]
Thanks for checking! This should definitely be accounted for. I just have to figure out how clang sees default arguments and get it to use those.

**Comment by lcorcodilos** [comment]
It was a bit tricky but I think I successfully set it up so it can automatically determine default arguments and plug those in. I'll be including the changes in PR #27 since there were other infrastructural changes that this feature relied on and had to change. I'll merge that PR first and then this one. Then I'll do a new release!

**Pull request merged**
