### PR TITLE
Adding exception to column not being present in Node.Cut

### PR DESCRIPTION
**Pull request by dmajumder**
the change should be pretty obvious. Not sure if this is handled somewhere else or whether this is the best implementation. 
Typical use case:
XToHY signal files do not all have the same values of MY and hence branches for those masses are missing. This exception handling seems to be the most straightforward way to run over all files without additional checks.

### CODE REVIEW

**Comment by dmajumder** [comment]
Thanks to @mroguljic the latest commit seems to be the right way to do a missing column check in HAMMER. This could possibly be implemented in some way in the downstream analyzer code however having a low level check+solution seems more fool-proof. Let us know if you think there's a tactical or philosophical problem with this implementation @lcorcodilos

**Comment by lcorcodilos** [comment]
I think implementing this in one form or another is a good idea since we'd like HAMMER to be as helpful to the analyzer as possible and, at the moment, there's no check that a column exists (and what to do if it doesn't exist). I have two concerns though (assuming I'm understanding this correctly). 

The first is with `cut.split('==')[0]`. This assumes that the C++ statement only ever evaluates `==` and that the left-hand side of the "equation" is always the branch name. If my `cut` argument was `"FatJet_pt[0] > 400"`, I would trigger the exception even though `FatJet_pt` is a column. I think this brings up an additional complication for when an index is being used like in `FatJet_pt[0]`. `FatJet_pt` is a column but `FatJet_pt[0]` is not (at least, I think that's how `HasColumn` will interpret it).

Assuming we iron out the above, my second concern is in how to interact with the user if the column name is missing. As written, there's an error printed but the program continues. My concern is that this could be crucially missed by someone who mis-typed a branch name and is using a substantial enough amount of printout when they run this in the background or in a batch job. Say someone has a working program with O(20-50) `Cut`s and `Define`s that they send to condor for processing. They get asked to add a new cut somewhere in the middle of the current workflow and so they add that along with a change in binning that they had been meaning to do (so that the distributions still change from the previous version). If they aren't double checking for the exception print out in the condor stdout, they will most likely not realize that their new cut is not being applied.

One final note is that whatever we decide to do should also be implemented for Node.Define so it may make sense to have an external function or class to parse the C++ strings and check for column names. I currently use clang in python to parse full C++ modules so we can use that to parse the single lines as well. I'd have to spend 15 minutes fiddling with it but I think we can just ask for the variable names in the string and cross check them against declared variables and column names. Then the function doing the clang parsing could take an option that tells the code to define the variable as a column full of zeros (or some user defined value) if it doesn't find a matching column. That way the behavior is deliberate by the user.

**Comment by dmajumder** [comment]
Thanks for the insights. It is great the we are on the right track and I agree that we should implement this in a more fool-proof way. This is a first attempt to unravel the design of this framework and we are already processing XtoHY signal events with this, so I thought it should be documented somehow (hence this PR). I will convert this to a draft PR while we keep working on making this more robust.

**Comment by dmajumder** [comment]
> Thanks for the insights. It is great the we are on the right track and I agree that we should implement this in a more fool-proof way. This is a first attempt to unravel the design of this framework and we are already processing XtoHY signal events with this, so I thought it should be documented somehow (hence this PR). I will convert this to a draft PR while we keep working on making this more robust.

**Pull request closed without merging**
